$engine: 3
$minFxVersion: 6230
$onesync: on
name: newdawn_recipe
version: 0.6.1
author: Lexinor
description: New Dawn RP

tasks:
  ## Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  - action: remove_path
    path: ./resources/[cfx-default]/[gamemodes]

  ## Download and prepare server.cfg, database and icon
  - action: download_github
    src: https://github.com/lexinor/lexinor_recipes
    ref: master
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/inventory.cfg
    dest: ./inventory.cfg

  - action: move_path
    src: ./tmp/recipe/ox_target.cfg
    dest: ./ox_target.cfg
  
  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/oxpog.png
    dest: ./oxpog.png

  - action: replace_string
    mode: all_vars
    file: ./tmp/recipe/esx.sql

  - action: connect_database
  - action: query_database
    file: ./tmp/recipe/esx.sql

# Download basic resources and ESX dependencies

  - action: download_github
    src: https://github.com/lexinor/esx-core
    ref: main
    dest: ./tmp/core

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    ref: main
    dest: ./tmp/addons/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    ref: main
    dest: ./tmp/addons/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    ref: main
    dest: ./tmp/addons/esx_datastore

  - action: download_github
    src: https://github.com/lexinor/esx_service
    ref: main
    dest: ./tmp/addons/esx_service

  - action: download_github
    src: https://github.com/lexinor/esx_basicneeds
    ref: main
    dest: ./tmp/addons/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_optionalneeds
    ref: main
    dest: ./tmp/addons/esx_optionalneeds

  - action: download_github
    src: https://github.com/lexinor/esx_property
    ref: main
    dest: ./tmp/addons/esx_property

  - action: download_github
    src: https://github.com/lexinor/esx_dmvschool
    ref: main
    dest: ./tmp/addons/esx_dmvschool

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    ref: main
    dest: ./tmp/addons/esx_billing

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    ref: main
    dest: ./tmp/addons/esx_joblisting

  - action: download_github
    src: https://github.com/lexinor/esx_banking
    ref: main
    dest: ./tmp/addons/esx_banking
  
  - action: query_database
    file: ./tmp/addons/esx_banking/banking.sql

  - action: download_github
    src: https://github.com/lexinor/esx_lscustom
    ref: main
    dest: ./tmp/addons/esx_lscustom

  - action: download_github
    src: https://github.com/lexinor/esx_society
    ref: main
    dest: ./tmp/addons/esx_society

  - action: waste_time # prevent github throttling
    seconds: 5

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    ref: main
    dest: ./tmp/addons/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    ref: main
    dest: ./tmp/addons/esx_status
    
  - action: download_github
    src: https://github.com/esx-framework/esx_sit
    ref: main
    dest: ./tmp/addons/esx_sit

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[esx]

  - action: move_path
    src: ./tmp/addons/
    dest: ./resources/[esx_addons]

  - action: remove_path
    path: ./resources/[esx]/esx_loadingscreen

  - action: remove_path
    path: ./resources/[esx]/esx_multicharacter

  - action: remove_path
    path: ./resources/[esx]/skinchanger

  - action: remove_path
    path: ./resources/[esx]/esx_example

  ## ox_lib
  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources

  ## oxmysql
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources

  ## ox_inventory new dawn fork
  - action: download_file
    url: https://github.com/NewDawn-RP/ox_inventory/releases/download/latest/ox_inventory.zip
    path: ./tmp/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources

  ## illenium-appearance
  - action: download_github
    src: https://github.com/lexinor/illenium-appearance
    ref: main
    dest: ./resources/illenium-appearance

  ## pefcl
  # - action: download_file
  #   ##url: https://github.com/project-error/pefcl/releases/latest/download/pefcl.zip
  #   url: https://github.com/lexinor/pefcl/releases/download/unstable-main/pefcl-pre-6c9aa49.zip
  #   path: ./tmp/pefcl.zip

  # - action: unzip
  #   src: ./tmp/pefcl.zip
  #   dest: ./resources/
  # - action: query_database
  #   file: ./resources/pefcl/import.sql

  # - action: move_path
  #   src: ./tmp/recipe/pefclconfig.json
  #   dest: ./resources/pefcl/config.json
  #   overwrite: true

  # ## pefcl-esx
  # - action: download_github
  #   src: https://github.com/lexinor/pefcl-esx
  #   ref: main
  #   dest: ./resources/pefcl-esx

  ## pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[voice]/pma-voice

  ## ac_radio
  - action: download_github
    src: https://github.com/lexinor/ac_radio
    ref: main
    dest: ./resources/[voice]/ac_radio

  ## screenshot-basic
  - action: download_github
    src: https://github.com/citizenfx/screenshot-basic
    ref: master
    dest: ./resources/[voice]/screenshot-basic

  ## loadingscreen
  - action: download_github
    src: https://github.com/lexinor/pe-basicloading
    ref: oxesx
    dest: ./resources/pe-basicloading

  - action: replace_string
    mode: all_vars
    file:
    - ./resources/pe-basicloading/web/config.js

  ## ipl loader
  - action: download_github
    src: https://github.com/lexinor/bob74_ipl
    ref: master
    dest: ./resources/[maps]/bob74_ipl

  ## ox_target
  - action: download_github
    src: https://github.com/overextended/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  ## ox_fuel
  - action: download_github
    src: https://github.com/lexinor/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  ## ox_doorlock
  - action: download_file
    url: https://github.com/lexinor/ox_doorlock/releases/latest/download/ox_doorlock.zip
    path: ./tmp/ox_doorlock.zip

  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./tmp/ox_doorlock

  - action: move_path
    src: ./tmp/ox_doorlock/ox_doorlock
    dest: ./resources/[ox]/ox_doorlock

  # ## PolyZone
  # - action: download_file
  #   url: https://github.com/mkafrin/PolyZone/releases/latest/download/PolyZone.zip
  #   path: ./tmp/PolyZone.zip
  # - action: unzip
  #   src: ./tmp/PolyZone.zip

  ## xsound
  - action: download_github
    src: https://github.com/lexinor/xsound
    ref: master
    dest: ./resources/[libraries]/xsound

  ## interact-sound
  - action: download_github
    src: https://github.com/lexinor/interact-sound
    ref: master
    dest: ./resources/[libraries]/interact-sound

  ## bulletin
  - action: download_github
    src: https://github.com/lexinor/bulletin
    ref: main
    dest: ./resources/[libraries]/bulletin

  ##- action: copy_path
  ##  src: ./tmp/bulletin/bulletin
  ##  dest: ./resources/[libraries]/bulletin

  ## rprogress
  - action: download_github
    src: https://github.com/lexinor/rprogress
    ref: master
    dest: ./resources/[libraries]/rprogress

  ## sublime_administration
  - action: download_github
    src: https://github.com/lexinor/sublime_administration
    ref: main
    dest: ./resources/[admin]/sublime_administration

  - action: query_database
    file: ./resources/[admin]/sublime_administration/db-Sublime.sql
  
  ## supv_core
  - action: download_github
    src: https://github.com/lexinor/supv_core
    ref: main
    dest: ./resources/[libraries]/supv_core

  - action: download_github
    src: https://github.com/lexinor/utk_render
    ref: main
    dest: ./resources/[libraries]/utk_render
    
  - action: download_github
    src: https://github.com/lexinor/pd-safe
    ref: master
    dest: ./resources/[libraries]/pd-safe
    
  - action: download_github
    src:  https://github.com/lexinor/mhacking
    ref: main
    dest: ./resources/[libraries]/mhacking

  - action: download_github
    src: https://github.com/lexinor/cd_easytime
    ref: main
    dest: ./resources/[general_scripts]/cd_easytime

 - action: download_github
    src: https://github.com/lexinor/vehiclefailure
    ref: main
    dest: ./resources/[general_scripts]/vehiclefailure  

  - action: download_github
    src: https://github.com/lexinor/animviewer
    ref: master
    dest: ./resources/[dev]/animviewer

  - action: download_github
    src: https://github.com/lexinor/wasabi_mining
    ref: main
    dest: ./resources/[jobs]/wasabi_mining

  - action: download_github
    src: https://github.com/lexinor/wasabi_fishing
    ref: main
    dest: ./resources/[jobs]/wasabi_fishing
    
  - action: download_github
    src: https://github.com/lexinor/pickle_farming
    ref: main
    dest: ./resources/[jobs]/pickle_farming
    
  - action: download_github
    src: https://github.com/lexinor/pickle_rental
    ref: main
    dest: ./resources/[jobs]/pickle_rental    

  - action: download_github
    src: https://github.com/lexinor/scully_emotemenu
    ref: main
    dest: ./resources/[general_scripts]/scully_emotemenu

  - action: download_github
    src: https://github.com/lexinor/flatbed_script
    ref: main
    dest: ./resources/[jobs]/[job-utils]/flatbed_script
    
  - action: download_github
    src: https://github.com/lexinor/taximeter
    ref: main
    dest: ./resources/[jobs]/[job-utils]/taximeter

  ## Final removals
  - action: remove_path
    path: ./tmp
