$engine: 3
$minFxVersion: 5104
$onesync: on
name: ox_esx_recipe
version: 1.7.0
author: Lexinor
description: Fork of ox_receipe Overextended ESX compatible with ox_inventory

tasks:
  ## Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  - action: remove_path
    path: ./resources/[cfx-default]/[gamemodes]

  ## Download and prepare server.cfg, database and icon
  - action: download_github
    src: https://github.com/lexinor/lexinor_recipes
    ref: master
    dest: ./tmp/recipe

  - action: move_path
    src: ./tmp/recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/recipe/oxpog.png
    dest: ./oxpog.png

  - action: replace_string
    mode: all_vars
    file: ./tmp/recipe/esx.sql

  - action: connect_database
  - action: query_database
    file: ./tmp/recipe/esx.sql

  ## Download bulk esx scripts
  - action: download_github
    src: https://github.com/lexinor/esx-legacy
    ref: main
    subpath: "[esx]"
    dest: ./resources/[esx]

  - action: download_github
    src: https://github.com/lexinor/esx-legacy
    ref: main
    subpath: "[esx_addons]"
    dest: ./resources/[esx_addons]

  ## esx_multicharacter
  - action: remove_path
    path: ./resources/[esx_addons]/esx_multicharacter

  - action: remove_path
    path: ./resources/[esx]/esx_multicharacter

  ## ox_lib
  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources

  ## oxmysql
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources

  ## ox_inventory
  - action: download_file
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
    path: ./tmp/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources
  ## fivem-appearance
  - action: download_github
    src: https://github.com/lexinor/fivem-appearance
    ref: main
    dest: ./resources/[ox]/fivem-appearance

  ## npwd
  - action: download_file
    url: https://github.com/project-error/npwd/releases/latest/download/npwd.zip
    path: ./tmp/npwd.zip
  - action: unzip
    src: ./tmp/npwd.zip
    dest: ./resources/

  - action: query_database
    file: ./resources/npwd/import.sql

  - action: remove_path
    path: ./resources/npwd/config.json

  - action: move_path
    src: ./tmp/recipe/npwdconfig.json
    dest: ./resources/npwd/config.json

  ## esx-npwd
  - action: download_github
    src: https://github.com/overextended/esx-npwd
    ref: main
    dest: ./resources/[voice]/esx-npwd

  ## pefcl
  - action: download_file
    url: https://github.com/project-error/pefcl/releases/latest/download/pefcl.zip
    path: ./tmp/pefcl.zip
  - action: unzip
    src: ./tmp/pefcl.zip
    dest: ./resources/
  - action: query_database
    file: ./resources/pefcl/import.sql

  - action: remove_path
    path: ./resources/pefcl/config.json

  - action: move_path
    src: ./tmp/recipe/pefclconfig.json
    dest: ./resources/pefcl/config.json

  ## pefcl-esx
  - action: download_github
    src: https://github.com/lexinor/pefcl-esx
    ref: main
    dest: ./resources/pefcl-esx

  ## pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[voice]/pma-voice

  ## rp-radio
  - action: download_github
    src: https://github.com/lexinor/rp-radio
    ref: master
    dest: ./resources/[voice]/rp-radio

  ## screenshot-basic
  - action: download_github
    src: https://github.com/project-error/screenshot-basic
    ref: master
    dest: ./resources/[voice]/screenshot-basic

  ## loadingscreen
  - action: download_github
    src: https://github.com/lexinor/pe-basicloading
    ref: oxesx
    dest: ./resources/pe-basicloading

  - action: replace_string
    mode: all_vars
    file:
    - ./resources/pe-basicloading/web/config.js

  ## ipl loader
  - action: download_github
    src: https://github.com/lexinor/bob74_ipl
    ref: master
    dest: ./resources/[maps]/bob74_ipl

  ## qtarget
  - action: download_github
    src: https://github.com/overextended/qtarget
    ref: main
    dest: ./resources/[ox]/qtarget

  ## ox_target
  - action: download_github
    src: https://github.com/overextended/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  ## ox_fuel
  - action: download_github
    src: https://github.com/overextended/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  ## ox_doorlock
  - action: download_file
    url: https://github.com/overextended/ox_doorlock/releases/latest/download/ox_doorlock.zip
    path: ./tmp/ox_doorlock.zip
  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./resources/[ox]/ox_doorlock

  ## PolyZone
  - action: download_file
    url: https://github.com/mkafrin/PolyZone/releases/latest/download/PolyZone.zip
    path: ./tmp/PolyZone.zip
  - action: unzip
    src: ./tmp/PolyZone.zip
    dest: ./resources/[libraries]/PolyZone    

  ## MenuV
  - action: download_github
    src: https://github.com/ThymonA/menuv
    ref: master
    dest: ./resources/[libraries]/menuv

  ## xsound
  - action: download_github
    src: https://github.com/lexinor/xsound
    ref: master
    dest: ./resources/[libraries]/xsound

  ## bulletin
  - action: download_github
    src: https://github.com/lexinor/bulletin
    ref: main
    dest: ./resources/[libraries]/bulletin

  ## rprogress
  - action: download_github
    src: https://github.com/lexinor/rprogress
    ref: master
    dest: ./resources/[libraries]/rprogress
    

  ## lexinor_dpemotes
  - action: download_github
    src: https://github.com/lexinor/lexinor_dpemotes
    ref: master
    dest: ./resources/[general_scripts]/lexinor_dpemotes
  - action: query_database
    file: /resources/[general_scripts]/lexinor_dpemotes/dpkeybinds.sql

  ## supv_core
  - action: download_github
    src: https://github.com/lexinor/supv_core
    ref: main
    dest: ./resources/[libraries]/supv_core

  ## cleanup
  - action: remove_path
    path: ./tmp
  - action: remove_path
    path: ./resources/[esx]/esx_skin
  - action: remove_path
    path: ./resources/[esx]/skinchanger
  - action: remove_path
    path: ./resources/[esx_addons]/esx_accessories
  - action: remove_path
    path: ./resources/[esx_addons]/esx_animations
  - action: remove_path
    path: ./resources/[esx_addons]/esx_barbershop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_clotheshop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_jobs
  - action: remove_path
    path: ./resources/[esx_addons]/esx_phone
  - action: remove_path
    path: ./resources/[esx_addons]/esx_shops
  - action: remove_path
    path: ./resources/[esx_addons]/esx_voice
  - action: remove_path
    path: ./resources/[esx_addons]/esx_weaponshop
  - action: remove_path
    path: ./resources/[esx_addons]/esx_whitelist
